name: Build a Massive Wiki with GitHub Actions 
run-name: ${{ github.actor }} is building a Massive Wiki

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Build-Massive-Wiki-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: |
             cd .massivewikibuilder/massivewikibuilder
             pip install -r requirements.txt

      - name: Build Static Pages
      - run: |
             cd .massivewikibuilder/massivewikibuilder
             ./mwb.py -c ../mwb.yaml -w ../.. -o ../output -t ../this-wiki-themes/basso

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: output 
          clean: true
